name: AI Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up LaTeX
        run: |
          choco install miktex.portable --source="'https://miktex.org/download/win'"  # Install MikTeX via Chocolatey

      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error "IntroIT Project Report.tex"


      - name: Rename PDF
        run: mv "IntroIT Project Report.pdf" "AI Project Report.pdf"


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ai-project-report 
          path: "AI Project Report.pdf"

